#name
name: First Pipeline

#when start
on:
  push:
    branches:
      - main

#jobs
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Print name
        run: echo "fatima"

      - name: today date
        run: date

      - name: files list
        run: ls

      - name: disk usage  
        run: df -h

  second-job:
    runs-on: ubuntu-latest
    needs: first-job
    steps:
      - name: Show Repo Files and Hostname
        run: | 
          echo "List all repo files"
          echo "List Hostname"
          ls -la
          hostname

  third-job:
    runs-on: ubuntu-latest
    needs: second-job
    steps:
      - name: Show Username
        run: uname
          